Add package cache replacement/retention process
OctopusDeploy/Calamari pull request #804
Opened 2021-12-06 06:09 UTC by desruc

todo

2021-12-10 05:30 UTC, desruc commented
Tests will fail at the moment. Waiting on finalized retention algorithm and paths to be set on packages.

2021-12-15 04:15 UTC, MissedTheMark requested changes
Couple of things to change, nothing huge.  Added some notes on how to get the free space tests to do what you need 👍

2021-12-15 04:15 UTC, MissedTheMark commented on source/Calamari.Tests/Fixtures/PackageRetention/JournalEntryFixture.cs
> +            // How do we simulate needing more disk space
You can use a real `IFreeSpaceChecker`, with a mock `IFileSystem` passed to it - and make the mock `fileSystem.GetDiskFreeSpace` call return the space you want it to.
Let me know if you want me to walk you through it.

2021-12-15 04:15 UTC, MissedTheMark commented on source/Calamari.Tests/Fixtures/PackageRetention/JournalEntryFixture.cs
> +            // How do we ensure the given package will be marked for removal?
Mock the retention algorithm to return the package you want to have removed.

2021-12-16 02:59 UTC, desruc commented on source/Calamari.Shared/Commands/ApplyDeltaCommand.cs
> +                packageJournal.ApplyRetention(PackageStore.GetPackagesDirectory());
> Given that we already have a check in `ApplyRetention`, perhaps we should add a dependency on the old FreeSpaceChecker there. Would make the calling code cleaner too if it's inside `ApplyRetention`

I've taken this approach.

`ApplyRetention` calls the old `EnsureDiskHasEnoughFreeSpace` method if package retention is disabled. I've also wrapped it in a try/catch.

2021-12-20 02:22 UTC, MissedTheMark approved these changes
👍

2021-12-20 22:19 UTC, merged